travis:
  secure:
    BINSTAR_TOKEN: j8qmllhdm8yAOt+oKx96J/Z0JdUt1VSjrYfMmIstr/NfrUIAt9vLOa2QRF2orL3QGrt8KtumsQzsA6+f4rwpSBGNpk/oO7/PJn5CqYQnI/uy++OFhxolVYWfjEghQTbz6/lUXX6pm2/NN8FkZuCQFfFRe3roSCBEoOrC9vlIbSwS6KCvNe0lHuFclgh9xx72MdF8Oon42zxE3WPJZ7XENNSmvEwSkp5AsEVrnW6vIGtgLp6zargLTnXGd+mpm1Vwj1tSNG3NrpBpK44kTmA+sNTJ9EGlub+ulIGpm7x658396KA7586PhLH8nZ8Susww+DrSTf/xXOzIRqr7ODzPm6EZE4TXHNYZF1Xj21Ul+HcljQSaG9DDNa4FC5kIekksE7quM/aTTruYRUbOqi0edRSdmVRBlJPCIdWZBtUEaYCNUwlSODGZFtKPjcRD/ajJEmsSfu3enFvYgeQOuHm+/FqxhI5KVBcBQ9oXl8Vm/WXEftjc0SbVzdJdH8mucnzdTbcSdZRZGCfUvXcUI+18uNCfDb7bEBz1lp1i2b/huIObOkl4zQ9UGECwbrWaRBRJpIE/EJWne7W5Av6gpv+knOGHmVcANWGGUBsj/qynrDkVhCoeT0clVXJAS1paatdvUvXXCw6IihLwjaoGQ/56/+TL+apMQceXpnFUtCCa8fM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
