travis:
  secure:
    BINSTAR_TOKEN: cyI2b2RmAiaJvC462Y9+ta5g6PagxPuT+dcMrPCl9B3EE4rfcteIqlMaWYMf3GfxrqzXbvg4jjFVrVWeqUSsOhRuDtbzcazS4b/Q5bgWmzktnpuQy1IUF5PJwsf9kRNC1QmbfmD/bzOCSNl3GmhSlHScdUE5SwVJFMj5i8Arm5/VeptCO7DSXP/RIfN36WMGA6RJF/EfAoUKkcElMkq2SJ/Ce/Di3FDo5Rm8pciAKtYiR1EZ31136xviOiF5zvkh7i5WAKuumtsUTwPvdmy+MTame+lMYKwHHlcczCfObSYZwh0SORkvF9sfIK1d11Mbadjm5hatZ9gbVF6zbS+cTsmlOpUNy/e4Zasieqmf/j7jiDfFbJZV/ROBosMGTqnNUBhgW42phIA/FCMZQKlVoT3i8kGLK8bfBmu/NJqKH/AYRYOhbwaD/Rxagbk7/sVXyusRs3UjMHRNoZM8bsQPX5SyDeoi7hL3p0XyBMFe9Jmz6X260sAd+hI0DyCwbWCSYPoiEyzFJj0bDGehK94oJYHdO1mvolXNIoR54DAcnCN54sDkrV9ras7yJlxiXtQzkc1aav6t2iRO5D9YSmzNsddox6V48h+urkW3bou2D6IimA4et8POHF79evPuJUIss/u6ntEhbiC00V2la0uy0Fca4pXyk603SihxJY9eqPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
